version: "3.8"
services:
  mysql:
    image: library/mysql:8.0.33
    ports:
      - 20000:3306
    volumes:
      - db-data:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yozm-cafe
      MYSQL_USER: ${DB_USERNAME:?}
      MYSQL_PASSWORD: ${DB_PASSWORD:?}
      TZ: Asia/Seoul

volumes:
  db-data:
