name: Client Test

on:
  push:
    branches: [main, dev]
    paths: client/**
  pull_request:
    branches: [main, dev]
    paths: client/**

jobs:
  deploy:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Use repository source
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn --frozen-lockfile
          parallel: true
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          command: yarn cypress:run
