name: Java build test

on:
  push:
    branches: [ main, dev ]
    paths: server/**
  pull_request:
    branches: [ main, dev ]
    paths: server/**

jobs:
  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: yozm-cafe
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 20000:3306

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
