name: Java build test

on:
  push:
    branches: [ main ]
    paths: server/**
  pull_request:
    branches: [ main ]
    paths: server/**

jobs:
  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: mirromutth/mysql-action@v1.1
        with:
          container port: 20000
          character set server: 'utf8mb4_general_ci'
          mysql database: 'yozm-cafe'
          mysql root password: 'root'
          mysql user: 'user'
          mysql password: 'password'
      - run: ./gradlew build
